prod:
  image: vizzuality/rw_adapter_arcgis:1.0.0${STAGING}
  command: start
  ports:
    - '3035'
  links:
    - redis
  env_file: prod.env

  log_driver: 'gelf'
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}

worker:
  image: vizzuality/rw_adapter_arcgis:1.0.0${STAGING}
  command: bundle exec sidekiq -e production -C config/sidekiq.yml
  volumes_from:
    - prod
  links:
    - redis
  env_file: prod.env

  log_driver: 'gelf'
  restart: always
  log_opt:
    gelf-address: ${GELF_ADDRESS}

redis:
  image: redis
  container_name: redis_rw_adapter_arcgis

